### ISSUE TITLE
Workflow executer: Handle task artefacts

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#52]
Workflow tasks use artefacts in two ways - as input, and as output. Artefacts can be files or directories, either the original payload that came from the Informatics Gateway or files that were generated by tasks in the workflow.

For more information about artefacts and how they're supposed to be used see the documentation: https://github.com/Project-MONAI/monai-deploy-workflow-manager/blob/develop/guidelines/mwm-workflow-spec.md#artifacts.

We need to support artefacts in the following ways:
- [x] Converting input artefact values from variable strings into concrete file paths, resulting in a mapping of artefact name to path
- [x] Provide the artefact map to the task executer
- [x] The task executer will then generate temporary credentials (not in scope for this ticket, see #112 ) and provide these to the task plug-in (See https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/129)
- [x] The task executer will receive output artefacts from the task plug-in and save their path in the task update status event (See https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/129)
- [x] The workflow executer, when handling the task update status event, will save the artefact information as part of the task execution object in MongoDB

**Acceptance criteria**

- GIVEN a task definition contains input artefacts WHEN the task is dispatched THEN the artefact values should be converted to a file path and included in the task dispatch event
- GIVEN the task definition contains an input artefact WHEN the artefact value references a non-existent artefact THEN it shouldn't be included in the artefact map (note: in the future we'll add the notion of mandatory artefacts, see #99)
- GIVEN a task update event contains an output artefacts map WHEN the task is updated THEN the output artefacts and their paths should be stored in MongoDB

**Implementation notes**

1. Artefact values can be one of the following:
1.1. `context.input` should be converted to the folder where the original payload has been stored. In the case of a DICOM input, that is the study folder.
1.2. `context.executions.TASK_ID.artifacts.ARTIFACT_NAME` should be converted to the path provided by the task plug-in for this artefact name in the output artefact map it provided when TASK_ID was wrapped up. These are "registered artefacts".
1.3 `context.executions.TASK_ID.output_dir` should be translated to the output directory of the referenced task
2. See #95 for more information on the task status update event. It is as part of handling the task status update that output artefacts should be registered.

**File structure**

The following structure should be used within MinIO:
```
BUCKET
- {{PAYLOAD_ID}}
-- dcm
-- fhr
-- workflows
--- {{WORKFLOW_INSTANCE_ID_1}}
---- {{execution_id_1}}
----- Files generated by execution 1
--- {{WORKFLOW_INSTANCE_ID_2}}
```

**Comment by mocsharp** [comment]
I'm still not quite clear about what the following translates to:
```
"value": "{{ context.executions.image_type_detector.artifacts.dicom }}"`
```
1. Does this translate to a single file path or a directory of files?
2. How would we know what `dicom` translates to? Do users register files they've generated as `dicom`? Or do we scan all the files for their type? (I assume not the latter).  Based on 1.2 of Implementation notes above, I assume these are registered by the user and the structure is to be defined in [this issue
](https://github.com/Project-MONAI/monai-deploy-messaging/issues/14).

---

> GIVEN a task update event contains an output artefacts map WHEN the task is updated THEN the output artefacts and their paths should be stored in MongoDB

Individual file path or the output directory that we provided to the application?

---
> Implementation notes 1.1

IG tries to put DICOM under `dcm/` and any HL7/FHIR under `ehr`. So, I think this is fine.

> Implementation notes 1.3

This is an output directory (e.g. some directory to a bucket on minio) provided by the Workflow Manager and mapped as `output artifacts` for Argo correct? 

---

IMO, both WM & TM do not care what files are there within each output directory.  However, the export services do need to know what they need to export at the file level.  Given that, we can simplify the output definition:

```
## Task A - entry task
"input": [
    {
      "name": "input_dicom", #this name must match the name defined in the Argo template in order to inject access credentials.
      "value": "{{ context.intput. }}" # 
    }
],
"output": [
      "dicom", #this name must match the name defined in the Argo template in order to inject access credentials.
      "ehr" #this name must match the name defined in the Argo template in order to inject access credentials.
]

## Task B

"input": [
    {
      "name": "input_dicom", #this name must match the name defined in the Argo template in order to inject access credentials.
      "value": "{{ context.executions.A.dicom }}" # where A is the name of Task A and dicom is the name of an output in Task A
    }
],
"output": [
   "fracture_report" #this name must match the name defined in the Argo template in order to inject access credentials.
]
```

**Comment by joshliberty** [comment]
1. @mocsharp the way I see it working is that the plug-in itself provides the dictionary of names to paths - those paths can either be specific files or folders, but either way they represent a single artefact. So in the following example: `{{ context.executions.image_type_detector.artifacts.dicom }}`, we are talking about the artefact "dicom" that the plug-in executing image_type_detector has registered. The name dicom here is purely incidental.
2. Regarding implementation note 1.3, yes, I'm talking about the output directory originally created by the workflow executer and provided to the task executer and the plug-in as the output directory.
3. Take a look at the specification around export destinations: https://github.com/Project-MONAI/monai-deploy-workflow-manager/blob/develop/guidelines/mwm-workflow-spec.md#export-destinations. When you are defining an export destination for task you're also specifying which artefacts should be sent to the export destination. That's different from the idea of defining output artefacts within the template, which I think doesn't give us anything.

**Comment by elleyouseewhy** [comment]
**ROADMAP DAYS: 4
ACTUAL DAYS:**

**Comment by RemakingEden** [comment]
### Tests

**All tests below with:**
- Directories
- Files

- Bucket with DICOM exists in MinIO, workflow requests sent with bucket name. Check the task dispatch message for valid input artefacts
- No bucket with DICOM exists in MinIO, workflow requests sent with bucket name. Workflow instance failed
- Create an artefact in MinIO, publish a task update message with the output artefact matching where we put the artefact in MinIO, check the workflow instance is updated with the correct filepath
- Create an artefact in MinIO, publish a task update message with the output artefact matching where we put the artefact in MinIO, check the task dispatch message is updated with the correct filepath
- No path, fail on required artefacts
- No artefact to resolve, fail on required artefacts

**Comment by RemakingEden** [comment]
Remaining to do on tests:
- Add multiple tests for folders/files

- Complete workflow instance assertion
- Complete task dispatch assertion

**Comment by mocsharp** [comment]
@jackschofield23 can we close this issue as complete?

**Comment by jackschofield23** [comment]
Closed
